//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\Me\Cybernetic\ComputerScience\4Year\2Semestre\SIM\Proyectos\3. Logica Difusa\Code\FuzzySolution\Fuzzy\Parsing\Fuzzy.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FuzzyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IFuzzyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>File</c>
	/// labeled alternative in <see cref="FuzzyParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] FuzzyParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SRule</c>
	/// labeled alternative in <see cref="FuzzyParser.fuzzy_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSRule([NotNull] FuzzyParser.SRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MTRule</c>
	/// labeled alternative in <see cref="FuzzyParser.fuzzy_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMTRule([NotNull] FuzzyParser.MTRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LAnd</c>
	/// labeled alternative in <see cref="FuzzyParser.logic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLAnd([NotNull] FuzzyParser.LAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LVarValue</c>
	/// labeled alternative in <see cref="FuzzyParser.logic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLVarValue([NotNull] FuzzyParser.LVarValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LOr</c>
	/// labeled alternative in <see cref="FuzzyParser.logic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLOr([NotNull] FuzzyParser.LOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LNot</c>
	/// labeled alternative in <see cref="FuzzyParser.logic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLNot([NotNull] FuzzyParser.LNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LParens</c>
	/// labeled alternative in <see cref="FuzzyParser.logic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLParens([NotNull] FuzzyParser.LParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AParens</c>
	/// labeled alternative in <see cref="FuzzyParser.arithmetic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAParens([NotNull] FuzzyParser.AParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AArithmetic</c>
	/// labeled alternative in <see cref="FuzzyParser.arithmetic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAArithmetic([NotNull] FuzzyParser.AArithmeticContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AVar</c>
	/// labeled alternative in <see cref="FuzzyParser.arithmetic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAVar([NotNull] FuzzyParser.AVarContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ANeg</c>
	/// labeled alternative in <see cref="FuzzyParser.arithmetic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitANeg([NotNull] FuzzyParser.ANegContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ANumber</c>
	/// labeled alternative in <see cref="FuzzyParser.arithmetic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitANumber([NotNull] FuzzyParser.ANumberContext context);
}
